name: marvel_app
description: "Aplicação Flutter que consome a API da Marvel para exibir informações detalhadas de personagens, como nome, descrição, quadrinhos, séries e filmes."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
